# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placyk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='name',
            field=models.CharField(choices=[('not defined', 0), ('Bronowice Małe', 1), ('Krowodrza', 2), ('Nowa Huta', 3)], default='not defined', max_length=64),
        ),
    ]
